### ISSUE TITLE
Testability

### ISSUE THREAD

**Issue by odd** [WegenenVerkeer/akka-persistence-postgresql#37]
How is the test suite supposed to work? I'm ready to create a PR with some setup and configuration changes but does not seem to get the `sbt-with-docker.sh` script to work. Are there other better ways of running the test suite?

**Comment by fg-devs** [comment]
Hey @odd,

I use docker compose for running the integration tests locally.

You basically only need the following two files in the project root:

_docker-compose.yml_:
```
version: '2.1'
services:
  db:
    image: postgres:9.4.10
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=akkapg
    - POSTGRES_PASSWORD=akkapg
    volumes:
    - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
```

_postgres-init.sql_:
```CREATE EXTENSION IF NOT EXISTS HSTORE;```
